version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: movie_booking_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=movie_booking
      - POSTGRES_USER=will
      - POSTGRES_PASSWORD=your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    container_name: movie_booking_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: movie_booking_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: