# Generated by Django 4.2.5 on 2025-09-29 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, db_column='Cast', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_column='Category', null=True, size=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_coming_soon',
            field=models.BooleanField(db_column='isComingSoon', default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_running',
            field=models.BooleanField(db_column='isRunning', default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='mpaa_rating',
            field=models.CharField(blank=True, db_column='MPAA_US_FILM_RATING', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.TextField(blank=True, db_column='Producer', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.TextField(blank=True, db_column='Reviews', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, db_column='Synopsis', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_pic_url',
            field=models.URLField(blank=True, db_column='TrailerPicLink', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, db_column='TrailerURL', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.TextField(blank=True, db_column='Director', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, db_column='Poster_img_URL', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(db_column='Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, db_column='Year', max_length=4, null=True),
        ),
    ]
