# Generated by Django 4.2.5 on 2025-10-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_add_showroom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='user',
        ),
        migrations.AddField(
            model_name='movieshow',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='paymentcard',
            table='payment_cards',
        ),
    ]
