# Generated by Django 4.2.5 on 2025-11-06 01:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_paymentcard_user_movieshow_price_and_more'),
    ]

    operations = [
    migrations.CreateModel(
        name='SeatHold',
        fields=[
            ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
            ('seat_id', models.UUIDField()),
            ('user_id', models.UUIDField()),
            ('showtime_id', models.UUIDField()),
            ('expires_at', models.DateTimeField()),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ],
        options={
            'db_table': 'seat_holds',
        },
    ),
    migrations.AddIndex(
        model_name='seathold',
        index=models.Index(fields=['showtime_id', 'seat_id'], name='seathold_showtime_seat_idx'),
    ),
    migrations.AddIndex(
        model_name='seathold',
        index=models.Index(fields=['expires_at'], name='seathold_expires_idx'),
    ),
]
