# Generated by Django 4.2.5 on 2026-02-02 19:28

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_add_seat_hold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': False},
        ),
        migrations.RenameIndex(
            model_name='seathold',
            new_name='seat_holds_showtim_15217f_idx',
            old_name='seathold_showtime_seat_idx',
        ),
        migrations.RenameIndex(
            model_name='seathold',
            new_name='seat_holds_expires_e81062_idx',
            old_name='seathold_expires_idx',
        ),
        migrations.AlterField(
            model_name='seathold',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
